name: 'Tukimatsu Chan - Japanese Month-End Detector'
description: 'Determines if today is the last business day of the month in Japan'
author: 'nikuteresa'
branding:
  icon: 'calendar'
  color: 'green'

outputs:
  is_last_business_day:
    description: 'True if today is the last business day of the month'
    value: ${{ steps.check_month_end.outputs.is_last_business_day }}
  executed_at:
    description: 'Current date in Japanese format (e.g., 2025年4月30日)'
    value: ${{ steps.check_month_end.outputs.executed_at }}

runs:
  using: 'composite'
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false
      
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        bundle install

    - name: Run month-end determination
      id: check_month_end
      shell: bash
      run: |
        # Run the month-end determination script
        ruby ${{ github.action_path }}/bin/determine_month_end.rb
