name: 'Month-End Determination'
description: 'Determines if today is the last business day of the month'
author: 'nikuteresa'
branding:
  icon: 'calendar'
  color: 'blue'

outputs:
  is_last_business_day:
    description: 'True if today is the last business day of the month'
    value: ${{ steps.check_month_end.outputs.is_last_business_day }}
  executed_at_getsumatsu_chan:
    description: 'Current year and month (e.g., 2025年4月5日)'
    value: ${{ steps.check_month_end.outputs.executed_at_getsumatsu_chan }}

runs:
  using: 'composite'
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false
      
    - name: Install dependencies
      shell: bash
      run: |
        bundle install

    - name: Run month-end determination
      id: check_month_end
      shell: bash
      run: |
        # Run the month-end determination script
        ruby ${{ github.action_path }}/bin/determine_month_end.rb
